spring:
  #配置redis
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-wait: 5000
        max-idle: 500
        min-idle: 0
    host: 42.192.56.20


server:
  port: 8081

security:
  oauth2:
    client:
      client-id: test
      client-secret: test123
      registered-redirect-uri: http://www.baidu.com